#! /usr/bin/env perl

use warnings;
use strict;

use Text::CSV;

my $mode = shift @ARGV or die;

sub save_hash ($$)
{
  if ($mode eq "preprocess")
    {
      my ($filename, $hash) = @_;
      my $fh = new IO::File $filename, "w" or die "$filename: $!";
      $fh->binmode (":utf8");

      my $index = 1;
    
      while (my ($k, $v) = each %$hash)
        {
          my (undef, $c) = @$v;
          do { print $fh "$k\t$index\t$c\n"; ++$index; } if $c > 1;
        }
    }
}

sub load_hash ($$)
{
  if ($mode ne "preprocess")
    {
      my ($filename, $hash) = @_;
      my $fh = new IO::File $filename, "r" or die "$filename: $!";
    
      while (defined ($_ = <$fh>))
        {
          chomp;
          my ($k, $n, $c) = split /\t/, $_, 3;
    
          $hash->{$k} = [$n, $c];
        }
    }
}

sub encode ($$)
{
  my ($v, $dict) = @_;

  if ($mode eq "preprocess")
    {
      $dict->{$v} ||= [ scalar keys %$dict, 0 ];
      ++$dict->{$v}->[1];
    }

  return exists $dict->{$v} ? $dict->{$v}->[0] : 1 + scalar keys %$dict;
}

sub tokenize ($)
{
  my ($s) = @_;

  return map { s/[0-9]+/0/g;
               substr ($_, 0, 7) } 
               split /[\s[:punct:]]+/, 
               lc ($s);
}

#----------------------------------------------------------------

my %vocab;

sub printexample ($$$$)
{
  my ($sid, $context, $query1, $query2) = @_;

  my @fullcontext = tokenize $context;
  my @context = @fullcontext > 40 ? splice @fullcontext, -40 : @fullcontext;
  my @fullquery1 = tokenize $query1;
  my @query1 = @fullquery1 > 40 ? splice @fullquery1, 40 : @fullquery1;
  my @fullquery2 = tokenize $query2;
  my @query2 = @fullquery2 > 40 ? splice @fullquery2, 40 : @fullquery2;

  my $ml = "|MultiLabel 1 0";

  while (@context || @query1 || @query2)
    {
      my $ct1 = @context ? "|Context @{[encode (shift @context, \%vocab)]}:1" : "";
      my $qt1 = @query1 ? "|Query1 @{[encode (shift @query1, \%vocab)]}:1" : "";
      my $qt2 = @query2 ? "|Query2 @{[encode (shift @query2, \%vocab)]}:1" : "";

      print "$sid $ct1 $qt1 $qt2 $ml\n";

      $ml = "";
    }
}

#----------------------------------------------------------------

my $vocabfile = "shortvocab3";

load_hash ($vocabfile, \%vocab);

my $csv = Text::CSV->new ({ binary => 1 }) or die Text::CSV->error_diag ();

# eat header
<>;

my $sid = 1;
my $maxsid = $mode eq "megatrain" || $mode eq "preprocess" ? 200000 : 20000;
my @positives;
my @negatives;

while (my $row = $csv->getline (*ARGV))
  {
    my @fields = @$row;

    printexample ($sid, $fields[0], $fields[1], $fields[2]);

    last if ++$sid > $maxsid;
  }

save_hash ($vocabfile, \%vocab);
